site_name: Engineering Way of Working (WoW) 🛠️
site_description: 'Standardised guides, templates, and architectural process documentation (ADRs, C4, arc42) for our engineering and delivery lifecycle.'
site_url: ""

theme:
  name: material  
  locale: en
  features:
    - navigation.instant
    - navigation.tracking
    - toc.integrate 
    - navigation.expand
    - content.width.full

docs_dir: docs
site_dir: site

exclude_docs: ""

plugins:
  - gen_nav:
      enabled: true
  - search
  - awesome-pages
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: false
      type: timeago
  - glightbox

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - plantuml_markdown:
      format: svg
      cachedir: .plantuml-cache
      # Uses PLANTUML_JAR env var
