#!/usr/bin/env python3
"""
join_book.py

Join a structured Markdown book directory into a single Markdown file.

Features:
- Deterministic ordering
- Supports front matter, parts, chapters, back matter
- Dry-run mode
- Idempotent output
- No renumbering or content rewriting

Usage:
    python join_book.py book/ output.md [--dry-run]
"""

from pathlib import Path
import argparse


GENERATED_MARKER = "<!-- AUTOGENERATED: joined book -->"


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8").rstrip()


def write(path: Path, content: str, dry_run: bool) -> None:
    if dry_run:
        print(f"[DRY-RUN] write {path}")
        return
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def main(book_dir: Path, output_md: Path, dry_run: bool) -> None:
    parts = []
    output = []

    output.append(GENERATED_MARKER)
    output.append("")

    # Root-level files (front matter, intro, back matter)
    root_files = sorted(
        p for p in book_dir.iterdir()
        if p.is_file() and p.suffix == ".md"
    )

    for file in root_files:
        output.append(read(file))
        output.append("")

    # Part directories
    part_dirs = sorted(
        p for p in book_dir.iterdir()
        if p.is_dir() and p.name.startswith("part-")
    )

    for part_dir in part_dirs:
        part_files = sorted(
            p for p in part_dir.iterdir()
            if p.is_file() and p.suffix == ".md"
        )

        for file in part_files:
            output.append(read(file))
            output.append("")

    write(output_md, "\n".join(output), dry_run)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("book_dir", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    main(args.book_dir, args.output, args.dry_run)
